---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    targetRevision: 2023.10.4
    chart: authentik
    helm:
      releaseName: authentik
      values: |
        authentik:
          error_reporting:
            enabled: false
        ingress:
          annotations:
            nginx.ingress.kubernetes.io/configuration-snippet: |
              more_set_headers "Content-Security-Policy: default-src 'none'; script-src 'self' 'unsafe-inline' 'https://challenges.cloudflare.com/turnstile/v0/api.js?compat=recaptcha'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; font-src 'self' data:; base-uri 'none'; form-action 'self'; frame-ancestors 'none';  upgrade-insecure-requests";
          ingressClassName: nginx
          enabled: true
          tls:
            - hosts:
                - id.realliance.net
              secretName: id-tls
          hosts:
            - host: id.realliance.net
              paths:
                - path: "/"
                  pathType: Prefix
        redis:
          enabled: true
        email:
          host: smtp.sendgrid.net
          port: 587
          username: apikey
          use_tls: true
          timeout: 30
          from: no-reply@realliance.net
        env:
          AUTHENTIK_POSTGRESQL__HOST: psql
          AUTHENTIK_POSTGRESQL__NAME: postgres
        envValueFrom:
          AUTHENTIK_SECRET_KEY:
            secretKeyRef:
              name: authentik
              key: AUTHENTIK_SECRET_KEY
          AUTHENTIK_POSTGRESQL__USER:
            secretKeyRef:
              name: postgres.acid-authentik.credentials.postgresql.acid.zalan.do
              key: username
          AUTHENTIK_POSTGRESQL__PASSWORD:
            secretKeyRef:
              name: postgres.acid-authentik.credentials.postgresql.acid.zalan.do
              key: password
          AUTHENTIK_EMAIL__PASSWORD:
            secretKeyRef:
              name: authentik
              key: AUTHENTIK_EMAIL__PASSWORD

  destination:
    server: https://kubernetes.default.svc
    namespace: id
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
