---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recipes
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/realliance/kubernetes
    path: manifests/recipes
  destination:
    server: https://kubernetes.default.svc
    namespace: recipes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
