---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
    service: api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        service: api
    spec:
      securityContext:
        runAsUser: 101
        runAsGroup: 101
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
        - name: cache
          emptyDir:
            medium: Memory
      containers:
        - name: api
          image: ghcr.io/realliance/community-api:main@sha256:81ff49b90160c76c2c1e9e910a2448a72b81166d0d256b351836f890e877cd9c
          ports:
            - containerPort: 3000
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 101
            runAsGroup: 101
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /.cache
              name: cache
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - "./migrate.sh"
          env:
            - name: DB
              value: postgres
            - name: DATABASE_NAME
              value: postgres
            - name: DATABASE_HOST
              value: psql
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.acid-community.credentials.postgresql.acid.zalan.do
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    service: api
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: api
