---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
    service: api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        service: api
    spec:
      securityContext:
        runAsUser: 101
        runAsGroup: 101
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
        - name: cache
          emptyDir:
            medium: Memory
      containers:
        - name: api
          image: ghcr.io/realliance/community-api:main@sha256:6dc04bf1246faf7c0cb34d4007aa7948bc78bdfd8df92e22549632fb0875a6e4
          ports:
            - containerPort: 3000
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 101
            runAsGroup: 101
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: DB
              value: postgres
            - name: DATABASE_HOST
              value: psql
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.acid-community.credentials.postgresql.acid.zalan.do
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    service: api
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: api
