---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: community-ingress
  labels:
    service: web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Security-Policy: default-src 'none'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://id.realliance.net; font-src 'self' data:; base-uri 'none'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests";
spec:
  tls:
    - hosts:
        - community.realliance.net
      secretName: community-tls
  rules:
    - host: community.realliance.net
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: community-tls
  namespace: realmic
spec:
  secretName: community-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: community.realliance.net
  dnsNames:
    - community.realliance.net
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 384
