---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: community-ingress
  labels:
    service: web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "*"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_clear_headers "Content-Security-Policy";
spec:
  tls:
    - hosts:
        - community.realliance.net
      secretName: community-tls
  rules:
    - host: community.realliance.net
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: community-tls
  namespace: realmic
spec:
  secretName: community-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: community.realliance.net
  dnsNames:
    - community.realliance.net
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 384
