apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dex
  namespace: argocd
spec:
  encryptedData:
    dex.oidc.clientSecret: AgAYLtZ8Q4B8ivS+3ZwiRlnXlHniUUP4iBmbtejinWC6LNLokH6OQ6itXZ/3k/WN3wliIx1OB9wK6KlbvAk4TkhZwHFa2Xjy3LpL6+ReSzgken+1CTWkzFUbj61IXacOuoaN5nQNylVVlU0wOz7f+DmJkmUrfcK0KxpcwVgsEwSIV95s/xTfEck8Yi1bhumS1qVOHLxF+YIbK4wHY0LHMkbQ2tOmgCZUMlhcjG7N9CYZ1l5uypzTCIbGOnFINrSXCK37zbQfAVEUs1IkaUGOeyv01KoMILQZSUYj8JwswPLjHS/4cwTu2FBW7rJmeDXRUZ1zMpbBIR5TqlBgjNmlpiK4mB7U0K1rNmPXrmNTzX1129kOfWDf9myH48u/SCZkHY/paTpg9rWextG0KJnwg/4FLgqrawS1lTNIVTbY2OSVwpKBYwqbu1DyhAwcKzu31/5+qf5K7hNvDX5v298r6FOvYM8Elbnphbzdljfsu+gTABwP5ZomG2oqKBTyi4M+8mMb/Ca8DlGPZ0gOgp8wtn1IJVq5UxR8hCLFKUy1wbT+a+YUoapyYbxKMnl4ivogfe+tJZLyLZdcQsKxz8wY/HKZn0c28UuTGgAmPr3GHBAbs4uZStxqNPrXSuecTZbi1uNG5DdEjf/br1PJBZsfvSPLNWB0rYYJMSnTEkFc0zFjEtwDMwE1wr3BYfOH/wfH72cTp3h3ja9vnXsID66eD0lN8BB+QYwIn2NVsSsXsDxe1iFqZwckPdZTpAB4Jx8Al/Hrwxf79v72vC01Imkfd/sqSVPzMEMyaWzwzkwX2e9GqtJSODB9ULq/L0ya9w/tOmxLqK6RkLfAmIt6QAnynSPPfBVsaEyO8qDcLAijV1u+Eg==
  template:
    metadata:
      creationTimestamp: null
      name: dex
      namespace: argocd

