---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-external
  namespace: argocd
  labels:
    service: web
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - cd.realliance.net
      secretName: argocd-tls
  rules:
    - host: cd.realliance.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: cd.realliance.net
  dnsNames:
    - cd.realliance.net
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 384
