---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: id-tls
  namespace: id
spec:
  secretName: id-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: id.realliance.net
  dnsNames:
    - id.realliance.net
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 384
