apiVersion: v2
name: cert-manager
description: Cert Manager
type: application
version: 1.8.0
appVersion: "1.8.0"

dependencies:
- name: cert-manager
  version: v1.11.0
  repository: https://charts.jetstack.io
