ingress-nginx:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
    config:
      enable-brotli: 'true'
      hsts: 'true'
      hsts-max-age: '63072000'
      hsts-preload: 'true'
      server-snippet: |
        ssl_prefer_server_ciphers off;
      server-tokens: 'false'
      ssl-early-data: 'false'
      use-geoip: 'false'
      use-geoip2: 'false'
      enable-ocsp: 'true'
      allow-snippet-annotations: 'true'
    addHeaders:
      Content-Security-Policy: default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; font-src 'self' data:;
        base-uri 'none'; form-action 'self'; frame-ancestors 'none';  upgrade-insecure-requests
      Expect-CT: max-age=63072000, enforce
      Permissions-Policy: interest-cohort=()
      Referrer-Policy: no-referrer
      X-Content-Type-Options: nosniff
      X-Frame-Options: deny
