---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home
  namespace: ace
  labels:
    app: home
    service: web
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      namespace: ace
      labels:
        app: home
        service: web
    spec:
      securityContext:
        runAsUser: 101
        runAsGroup: 101
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
        - name: cache
          emptyDir:
            medium: Memory
      containers:
        - name: home
          image: ghcr.io/uf-ace/ace_website:v0.4.0@sha256:d8a921ddbba25bc162aeaa3d1d084d721d7c15f6e943db133f9a22f51e3f8d00
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 101
            runAsGroup: 101
          env:
            - name: REACT_APP_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: site
                  key: REACT_APP_CHANNEL_ID
            - name: REACT_APP_HOME_VIDEO_EMBED_ID
              valueFrom:
                secretKeyRef:
                  name: site
                  key: REACT_APP_HOME_VIDEO_EMBED_ID
            - name: REACT_APP_URI
              valueFrom:
                secretKeyRef:
                  name: site
                  key: REACT_APP_URI
            - name: REACT_APP_YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: site
                  key: REACT_APP_YOUTUBE_API_KEY         
---
apiVersion: v1
kind: Service
metadata:
  name: home
  namespace: ace
  labels:
    service: web
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: home
