---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: realliance-ingress
  namespace: realliance
  labels:
    service: web
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - realliance.net
        - www.realliance.net
      secretName: realliance-tls
  rules:
    - host: realliance.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home
                port:
                  number: 80
    - host: www.realliance.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home
                port:
                  number: 80
