---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: realliance-tls
  namespace: realliance
spec:
  secretName: realliance-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: realliance.net
  dnsNames:
    - realliance.net
    - www.realliance.net
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 384
