---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: acid-recipes
  namespace: recipes
spec:
  databases:
    recipes: postgres
  numberOfInstances: 1
  spiloRunAsUser: 101
  spiloRunAsGroup: 103
  spiloFSGroup: 103
  postgresql:
    version: "13"
  teamId: acid
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 100m
  users:
    postgres: []
  volume:
    size: 4Gi
  patroni:
    pg_hba:
      - local     all  all  trust
      - host      all  all  0.0.0.0/0   md5
      - host      all  all  ::1/128     md5
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: recipes
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: psql
  selector:
    cluster-name: acid-recipes
