---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: notion-sync
spec:
  schedule: 0 */6 * * *
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 101
            runAsGroup: 101
          restartPolicy: Never
          containers:
            - name: backend
              image: ghcr.io/christopherjmiller/chatterbox:1.2.0@sha256:9cf4b76c8cb4b32c412dc761a17c781d12fae975121c3aecb1279ed8aaa47d05
              securityContext:
                readOnlyRootFilesystem: true
                runAsUser: 101
                runAsGroup: 101
              resources:
                requests:
                  memory: 64Mi
                  cpu: 50m
                limits:
                  memory: 64Mi
                  cpu: 50m
              envFrom:
                - secretRef:
                    name: notion-creds
              env:
                - name: DATABASE_ID
                  value: 5118f55805f148f3bba579335ead5bc7
                - name: DATABASE_DB
                  value: postgres
                - name: DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres.acid-chrismillerxyz.credentials.postgresql.acid.zalan.do
                      key: username
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres.acid-chrismillerxyz.credentials.postgresql.acid.zalan.do
                      key: password
                - name: DATABASE_HOST
                  value: acid-chrismillerxyz:5432
