---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: notion-sync
spec:
  schedule: 0 */6 * * *
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 101
            runAsGroup: 101
          restartPolicy: Never
          containers:
            - name: backend
              image: ghcr.io/christopherjmiller/chatterbox:1.1.0
              securityContext:
                readOnlyRootFilesystem: true
                runAsUser: 101
                runAsGroup: 101
              envFrom:
                - secretRef:
                    name: notion-creds
              env:
                - name: DATABASE_DB
                  value: postgres
                - name: DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres.acid-chrismillerxyz.credentials.postgresql.acid.zalan.do
                      key: username
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres.acid-chrismillerxyz.credentials.postgresql.acid.zalan.do
                      key: password
                - name: DATABASE_HOST
                  value: acid-chrismillerxyz:5432
