---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pack-tls
spec:
  secretName: pack-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: pack.realliance.net
  dnsNames:
    - pack.realliance.net
  privateKey:
    rotationPolicy: Always
    algorithm: ECDSA
    size: 384
