apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgAH4E/vJB5gi67V5JF5wX637g0WvmJyrqXfvYZYq078EC4b9U6GTicHC8GEXf5CmbdQCfKSqXDVdfytKDqh39JwP9OwwDFZ2kdtVW7zKuzbYFBjZyStxbAP3SVyr5wVskFRqYDM5ocMHIrV5DVG5N720j05ucFjpcBdbab3VZAyrQgAUJZhb4+t/ESz8KYNYLWTbD7o16U7eWHrVbXfey2VK+ytB9CIi1XX1VsVZvrYOMBiAZQE18eC+WLE+uQWjAFmJF+gxhZS7Db2EfmfK/G2cQ65hk+1cR2etpLwzbvQCzyasB//Cu9Q9QMpUak2daFxFD1eC6/0ilhHAOeQvr0RaSbvByGKnI7nCA7wCHOxaYoeTi39P+OZU7TIe7Zho0udPnGj/G7z2AIBj3+b9lTRv71HdtRM5r78Das+Z6uUUyanzl7mc7hIP4VK9uTtIgk+L0WJ+ZGRylivMno22kS8ouQuZ2pvNwX706nkQoJ7CGCW56H2mgrLxP+ZGhIXI9jizmcbSuKhOW96mmvlEPhhooaDay3TvJE28D7ljFoRnIHOh8R9hGog9LpIiVuMwbrUyxvUhOUXKWq6uf02w8njif076NSWzU2TCUHtt9m8BFa4eI5S4yt6gk11Q5SxoIjPXAGT/OfWqMBgIzAhvbHMEnMQHwF8+wJdlWQgnDvO1Cyx69M6iH4UyiDSVPSG2mDyvPZNtmaBm9ciPxSp7DwvAQ5segHLMrKO3S3guUf6j7/mWpj+mFuV
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns

