---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
bases:
  - github.com/kubernetes-sigs/external-dns/kustomize
resources:
  - namespace.yaml
  - cloudflare-api-token.yaml
patchesStrategicMerge:
  - external-dns-deployment.yaml
